use super::*;

/// Canonical CLI hierarchy consumed by parsing, completion, and qualification.
pub const CLI_CHILDREN: &[(&str, &[&str])] = &[
    ("hosts", &["sources", "silent"]),
    (
        "sessions",
        &[
            "search",
            "abuse",
            "correlate",
            "blocks",
            "context",
            "tools",
            "projects",
            "index",
            "add",
            "watch",
            "checkpoints",
            "errors",
            "prunecheckpoints",
            "doctor",
            "watchstatus",
            "smokewatch",
            "similar",
            "incidentcontext",
            "incidents",
            "investigate",
            "assess",
            "llminvocations",
            "skills",
            "skillincidents",
            "skillinvestigate",
            "skillassess",
            "mcpevents",
            "mcpincidents",
            "mcpinvestigate",
            "mcpassess",
            "hookevents",
            "hookincidents",
            "hookinvestigate",
            "hooksbackfill",
        ],
    ),
    ("assess", &["skill", "abuse", "mcp", "hooks"]),
    (
        "analysis",
        &["errors", "incident", "patterns", "anomalies", "compare"],
    ),
    ("state", &["host", "fleet", "clockskew"]),
    (
        "ingest",
        &["shell", "inventory", "filetail", "syslog", "docker"],
    ),
    ("ingest shell", &["user", "agent"]),
    ("ingest shell user", &["index", "atuinindex"]),
    ("ingest shell agent", &["index", "wrap"]),
    ("ingest inventory", &["refresh", "status"]),
    (
        "ingest filetail",
        &["list", "status", "add", "remove", "enable", "disable"],
    ),
    ("ingest syslog", &["status"]),
    ("ingest docker", &["status", "sources"]),
    ("alerts", &["signatures", "notifications"]),
    ("alerts signatures", &["list", "ack", "unack"]),
    ("alerts notifications", &["recent", "test"]),
    ("heartbeat", &["agent"]),
    ("correlate", &["events", "state", "topic"]),
    ("stats", &["summary", "ingestrate"]),
    (
        "compose",
        &["status", "doctor", "up", "down", "restart", "pull", "logs"],
    ),
    (
        "setup",
        &[
            "check",
            "repair",
            "install",
            "pluginhook",
            "sessionstimer",
            "sessionswatch",
            "sessionshealth",
            "shell",
            "heartbeatagent",
            "debugwrapper",
            "debugcompose",
            "deploy",
            "doctor",
        ],
    ),
    ("setup shell", &["agent", "completions"]),
    ("setup shell agent", &["install", "remove", "check"]),
    ("setup shell completions", &["install", "remove", "check"]),
    ("setup sessionstimer", &["install", "remove", "check"]),
    ("setup sessionswatch", &["install", "remove", "check"]),
    ("setup heartbeatagent", &["install", "remove", "check"]),
    ("setup debugwrapper", &["install", "remove", "check"]),
    ("setup debugcompose", &["install", "remove", "check"]),
    ("setup deploy", &["preflight", "local", "remote", "agent"]),
    ("update", &["server", "clients", "all", "config"]),
    ("update config", &["server", "clients"]),
    ("doctor", &["binary"]),
    (
        "db",
        &["status", "integrity", "checkpoint", "vacuum", "backup"],
    ),
    ("db integrity", &["status"]),
    ("config", &["get", "set", "unset", "list"]),
    (
        "graph",
        &["around", "explain", "evidence", "status", "rebuild"],
    ),
];

pub const CLI_ROOTS: &[&str] = &[
    "search",
    "filter",
    "tail",
    "hosts",
    "sessions",
    "assess",
    "analysis",
    "state",
    "status",
    "ingest",
    "alerts",
    "entity",
    "graph",
    "heartbeat",
    "correlate",
    "stats",
    "compose",
    "setup",
    "db",
    "config",
    "timeline",
    "apps",
    "artifactevents",
    "completions",
];

pub fn cli_children(path: &str) -> &'static [&'static str] {
    CLI_CHILDREN
        .iter()
        .find_map(|(parent, children)| (*parent == path).then_some(*children))
        .unwrap_or(&[])
}

pub const INGEST_SURFACES: &[(&str, SurfaceAccess, MutationClass)] = &[
    ("syslog-udp", SurfaceAccess::Info, MutationClass::AppendOnly),
    ("syslog-tcp", SurfaceAccess::Info, MutationClass::AppendOnly),
    (
        "POST /v1/logs",
        SurfaceAccess::Read,
        MutationClass::AppendOnly,
    ),
    (
        "POST /v1/metrics",
        SurfaceAccess::Read,
        MutationClass::AppendOnly,
    ),
    (
        "POST /v1/traces",
        SurfaceAccess::Read,
        MutationClass::AppendOnly,
    ),
    (
        "POST /v1/heartbeats",
        SurfaceAccess::Read,
        MutationClass::AppendOnly,
    ),
    (
        "POST /v1/agent-commands",
        SurfaceAccess::Read,
        MutationClass::AppendOnly,
    ),
    (
        "POST /v1/shell-history",
        SurfaceAccess::Read,
        MutationClass::AppendOnly,
    ),
    (
        "POST /v1/ai-transcripts",
        SurfaceAccess::Read,
        MutationClass::AppendOnly,
    ),
    (
        "POST /v1/syslog-forward",
        SurfaceAccess::Read,
        MutationClass::AppendOnly,
    ),
    ("file-tail", SurfaceAccess::Admin, MutationClass::Reversible),
    (
        "agent-docker",
        SurfaceAccess::Read,
        MutationClass::AppendOnly,
    ),
    (
        "GET /v1/agent/binary",
        SurfaceAccess::Read,
        MutationClass::None,
    ),
    (
        "GET /v1/agent/release",
        SurfaceAccess::Read,
        MutationClass::None,
    ),
    ("GET /health", SurfaceAccess::Info, MutationClass::None),
    ("GET /health/full", SurfaceAccess::Read, MutationClass::None),
    ("GET /app", SurfaceAccess::Info, MutationClass::None),
    (
        "GET /app/investigate",
        SurfaceAccess::Info,
        MutationClass::None,
    ),
    (
        "GET /app/assets/{*path}",
        SurfaceAccess::Info,
        MutationClass::None,
    ),
    ("GET /app/{*path}", SurfaceAccess::Info, MutationClass::None),
    ("POST /mcp", SurfaceAccess::Read, MutationClass::None),
    (
        "GET /.well-known/oauth-authorization-server",
        SurfaceAccess::Info,
        MutationClass::None,
    ),
    (
        "GET /.well-known/oauth-protected-resource",
        SurfaceAccess::Info,
        MutationClass::None,
    ),
    (
        "GET /mcp/.well-known/oauth-authorization-server",
        SurfaceAccess::Info,
        MutationClass::None,
    ),
    (
        "GET /mcp/.well-known/openid-configuration",
        SurfaceAccess::Info,
        MutationClass::None,
    ),
    (
        "GET /mcp/.well-known/oauth-protected-resource",
        SurfaceAccess::Info,
        MutationClass::None,
    ),
    ("GET /jwks", SurfaceAccess::Info, MutationClass::None),
    (
        "POST /register",
        SurfaceAccess::Info,
        MutationClass::AppendOnly,
    ),
    ("GET /authorize", SurfaceAccess::Info, MutationClass::None),
    ("GET /auth/login", SurfaceAccess::Info, MutationClass::None),
    (
        "GET /auth/google/callback",
        SurfaceAccess::Info,
        MutationClass::None,
    ),
    (
        "POST /token",
        SurfaceAccess::Info,
        MutationClass::AppendOnly,
    ),
];

pub const OAUTH_ROUTE_BINDINGS: &[&str] = &[
    "GET /.well-known/oauth-authorization-server",
    "GET /.well-known/oauth-protected-resource",
    "GET /jwks",
    "GET /authorize",
    "GET /auth/login",
    "GET /auth/google/callback",
    "POST /token",
    "POST /register",
];
